module.exports = {
	USER_CONNECTED    : 'USER_CONNECTED',
	USER_DISCONNECTED : 'USER_DISCONNECTED',
	MESSAGE_RECEIVED  : 'MESSAGE_RECIEVED',
	MESSAGE_SENT      : 'MESSAGE_SENT',
	TYPING            : 'TYPING',
	VERIFY_USER       : 'VERIFY_USER',
	LOGOUT            : 'LOGOUT',
	CREATE_CHATROOM   : 'CREATE_CHATROOM',
	JOIN_CHATROOM:      'JOIN_CHATROOM',
	NEW_CHATROOM      : 'NEW_CHATROOM',
	FOUND_CHATROOM    : 'FOUND_CHATROOM'
};
